on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6]

    container:
      image: python:3.6.9-stretch

    services:
      redis:
        image: redis

    steps:
    - uses: actions/checkout@v1
    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the test script
      run: |
        python src/main.py