on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    container:
      image: python:3.6.9-stretch

    services:
      redis:
        image: redis

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the test script
      run: |
        python src/main.py